### ISSUE TITLE
Hard for some people to find the music

### ISSUE THREAD

**Issue by ShuoZhang-dev** [MusicAsLanguage/mobileapp#130]
It was not obvious that music would be in the Tool Box.

Solutions could include:
•	mentioning the tool box in the lessons and activities
•	Renaming tool box (Music Box? but there might well be a range of tools; this is only hard until you know where to look)

**Comment by mpmikesell** [comment]
We decided tonight on "Music box" as the new name. Michael recommends two words and sentence casing rather than title casing--which is why lowercase "b" in "box". However, the app is not consistently formatted for sentence case yet, so title case ("Music Box") might be more appropriate in the short term. :)
